name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 22

      - name: install dependencies
        run: pnpm install

      - name: lint code
        run: pnpm lint && pnpm lint:types

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: build packages
        run: pnpm build
      - name: run tests
        run: pnpm test:coverage
        env:
          VITE_ANVIL_FORK_URL: ${{ vars.VITE_ANVIL_FORK_URL }}
          VITE_ANVIL_BLOCK_NUMBER: ${{ vars.VITE_ANVIL_BLOCK_NUMBER }}
          VITE_ANVIL_SAFE_ADDRESS: ${{ vars.VITE_ANVIL_SAFE_ADDRESS }}
          VITE_TEST_ADDRESS: ${{ vars.VITE_TEST_ADDRESS }}

        # run coverage only on ubuntu
      - name: Coveralls
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./coverage/lcov.info